language: perl
perl:
  - "5.24"
  - "5.12"
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1   # enables coverage+coveralls reporting
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
    #tags: true
    perl: 5.24
