language: perl
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1   # enables coverage+coveralls reporting
    - perl: 5.12
      env: COVERAGE=0 
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - cpanm -v CPAN::Uploader
  - cpanm -v Devel::Cover
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION zstd dsrc fqzcomp
  - source activate test-env
deploy:
  provider: script
  script: ./Build deploy
  skip_cleanup: true
  on:
    branch: master
    tags: true
    perl: 5.24
